config/routes.rb
Rails.application.routes.draw do
  # get '/users', to: 'users#index'
  # get '/users/:id', to: 'users#show'
  # get '/users/new', to: 'users#new'
  # post '/users', to: 'users#create'
  # get '/users/:id/edit', to: 'users#edit'
  # patch '/users/:id', to: 'users#update'
  # delete '/users/:id', to: 'users#destroy'

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    User.create(user_params)
    redirect_to(users_path)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to(users_path)
  end

  def destroy
    user = User.find(params[:id])
    user.delete
    redirect_to(users_path)
  end

  private

  def user_params
    params.require(:user).permit(:name, :age, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudSample04</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>編集</h1>
<%= form_for @user, url: user_path(@user.id), html: {method: :patch} do |f| %>
<p>名前:<%= f.text_field :name %></p>
<p>年齢:<%= f.text_field :age %></p>
<p>住所:<%= f.text_field :address %></p>
<input type="submit" value="送信">
<% end %>

app/views/users/index.html.erb
<%= link_to("新規登録", new_user_path) %>
<% @users.each do |user| %>
  <p>
    <%= user.name %>
    <%= user.age %>
    <%= user.address %>
    <%= link_to "詳細", user_path(user.id) %>
    <%= link_to "編集", edit_user_path(user.id) %>
    <%= link_to "削除", user_path(user.id), method: :delete, data: {confirm: "削除しますか？"} %>
  </p>
<% end %>

app/views/users/new.html.erb
<h1>新規登録</h1>
<%= form_for @user, url: users_path, html: {method: :post} do |f| %>
<p>名前:<%= f.text_field :name %></p>
<p>年齢:<%= f.text_field :age %></p>
<p>住所:<%= f.text_field :address %></p>
<input type="submit" value="送信">
<% end %>

app/views/users/show.html.erb
<h1>詳細情報</h1>
<p>名前:<%= @user.name %></p>
<p>年齢:<%= @user.age %></p>
<p>住所:<%= @user.address %></p>
<p><%= link_to "一覧ページへ", users_path %></p>